apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-gpu-model-cache
  labels:
    app.kubernetes.io/name: vllm
    app.kubernetes.io/component: model-cache
    app.kubernetes.io/part-of: gpu-ai-inference
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 20Gi