apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
  labels:
    app.kubernetes.io/name: vllm
    app.kubernetes.io/component: model-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vllm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vllm
        app.kubernetes.io/component: model-server
    spec:
      containers:
        - name: vllm
          image: vllm/vllm-openai-cpu:latest-x86_64
          args:
            - --model
            - meta-llama/Llama-3.2-1B-Instruct
            - --served-model-name
            - llama-3.2-1b-instruct
          ports:
            - name: http
              containerPort: 8000